config/routes.rb
Rails.application.routes.draw do
  root "chatroom#index"
  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  delete 'logout', to: 'sessions#destroy'
  post 'message', to: 'messages#create'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: true

  scope :custom_display, -> { order(:created_at).last(20) }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  
  validates :username, presence: true, length: { minimum: 3, maximum: 15 },
              uniqueness: {case_sensitive: false}
  has_secure_password

  VALID_EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i # const
  validates :email, uniqueness: { case_sensitive: false },
                    presence: true,
                    length: { maximum: 105 },
                    format: { with: VALID_EMAIL_REGEX }

  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def requere_user
    if !logged_in?
      flash[:error] = "You are must be logged in to perform this action"
      redirect_to login_path
    end
  end

end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :requere_user

  def index
    @message = Message.new
    @messages = Message.custom_display
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :requere_user

  def create
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast "chatroom_channel",
                                    mod_message: message_render(message)
    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def message_render(message)
    render(partial: 'message', locals: { message: message} )
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(username: session_params[:username])
    if user && user.authenticate(session_params[:password])
      session[:user_id] = user.id

      flash[:success] = "Logged in succesfully"
      redirect_to root_path
    else
      flash.now[:error] = "There was something wrong with your login details."
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Logged out"
    redirect_to login_path
  end

  private

  def session_params
    params.require(:session).permit(:username, :password)
  end

  def logged_in_redirect
    if logged_in?
      flash[:error] = "You are aleready logged in"
      redirect_to root_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :requere_user, only: [:edit, :update]
  before_action :requere_same_user, only: [:edit, :update, :destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the Alpha Blog #{@user.username}, you have succesfully sign up!"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "User was updated succesfuly."
      redirect_to @user
    else
      render 'edit'
    end
  end

  def show

  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:success] = "Account successfuly deleted"
    redirect_to root_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def requere_same_user
    if current_user != @user && !current_user.admin?
      flash[:error] = "You can only edit or delete your own account"
      redirect_to @user
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chatroom/index.html.erb
<h4 class="ui center aligned medium icon header">
  <i class="orange circular coffee icon"></i>
  Say Something
</h4>

<div class="ui two column grid ">
  <div class="twelve wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content" id="messages">
        <div class="ui feed" id="message-container">

            <%= render @messages %>

        </div>
      </div>

      <div class="extra content">

        <%= form_for(@message, html: {class: "ui reply form", role: "form"}, url: message_path, remote: true) do |f| %>
          <div class="field">
            <div class="ui fluid icon input">
              <%= f.text_field :body %>
              <%= f.button '<i class="bordered inverted orange edit icon"></i>'.html_safe %>

            </div>
          </div>
        <% end %>

      </div>

    </div>
  </div>

  <div class="four wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
        <div class="ui inverted vertical menu">
          <a class="active item">
            Home
          </a>
          <a class="item">
            Messages
          </a>
          <a class="item">
            Friends
          </a>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
<div class="ui <%= name %> message transition">
  <i class="close icon"></i>
  <div class="header">
    <%= msg %>
  </div>
</div>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Chatroom", root_path, class: "item" %>
<%= link_to "Messages", root_path, class: "item" %>
<div class="right menu">
  <div class="ui dropdown item">
    Account <i class="dropdown icon"></i>
    <div class="menu">
      <% if logged_in? %>
        <%= link_to "Log out", logout_path, method: :delete, class: "item" %>
      <% else %>
        <%= link_to "Log in", login_path, class: "item" %>
      <% end %>
    </div>
  </div>
  <% if !logged_in? %>
    <div class="item">
      <%= link_to "Log in", login_path, class: "ui primary button" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="ui small inverted menu">
      <div class="ui container">
        <%= render 'layouts/navigation' %>
      </div>
    </div>

    <div class="ui container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
       <em><%=message.user.username%></em>: <%=message.body%>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>


  <div class="ui form">
    <div class="ui message">
      <div class="header">The folowing errors prevented the <%= obj.class.name.downcase %> from beeing saved</div>
      <ul class="list">
        <% obj.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>

<% end %>

app/views/users/new.html.erb
<h4 class="ui center aligned medium icon header">
  Sign Up
</h4>

<%= render "shared/errors", obj: @user %>

<%= form_with(model: @user, class: "ui form", local: true, role: "form", url: signup_path) do |f| %>
  <div class="field">
    <%= f.label :username, "Username" %>
    <div class="ui left icon input">
      <%= f.text_field :username, placeholder: "Username" %>
      <i class="user icon"></i>
    </div>
  </div>
  <div class="field">
    <%= f.label :email, "Email" %>
    <div class="ui left icon input">
      <%= f.email_field :email, placeholder: "Email" %>
      <i class="mail icon"></i>
    </div>
  </div>
  <div class="field">
    <%= f.label :password, "Password" %>
    <div class="ui left icon input">
      <%= f.password_field :password, placeholder: "Password" %>
      <i class="lock icon"></i>
    </div>
  </div>
  <%= f.button "Sign up", class: "ui orange submit button" %>
<% end %>